apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
  labels:
    name: secret-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: secret2
  containers:
  - name: ssh-test-container
    image: busybox
    command:
      - sleep
      - "36000"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"

