apiVersion: apps/v1
kind: Deployment
metadata:
  name: whizlabs-dep-example
  labels:
    apps: wlrseg1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wlrseg1
  template:
    metadata:
      labels:
        app: wlrseg1
    spec:
      containers:
      - name: wlhello
        image: nginxdemos/hello
        ports:
        - containerPort: 80