apiVersion: v1
kind: Pod
metadata:
  name: my-pod3
  labels:
    name: cm-pod
spec:
  containers:
  - name: ssh-test-container
    image: busybox
    command:
      - sleep
      - "3600"
    env:
      - name: MY_ENV_VARIABLE
        valueFrom:
          configMapKeyRef:
            name: configmap2
            key: configmap-key1