apiVersion: v1
kind: Pod
metadata:
  name: whizlabs-pod-example-1
  labels:
    app.kubernetes.io/name: wlrseg2
spec:
  initContainers:
  - name: wlhello1
    image: nginxdemos/hello 
    ports:
    - containerPort: 80
  initContainers:
  - name: wlhello2
    image: nginxdemos/hello
    ports:
    - containerPort: 80
  containers:
  - name: wlhello2
    image: nginxdemos/hello
    ports:
    - containerPort: 80