apiVersion: v1
kind: Pod
metadata:
  name: whizlabs-pod-example-3
  labels:
    app.kubernetes.io/name: wlrseg2
spec:
  initContainers:
  - name: init-wait5m
    image: busybox:1.36
    command: ['sh', '-c', 'sleep 5m']
  containers:
  - name: wlhello2
    image: nginxdemos/hello
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20