apiVersion: v1
kind: Pod
metadata: 
  name: annopod
  annotations:
    k8slink: "https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/"
spec: 
  containers:
  - name: annocontainer
    image: nginx
    ports: 
    - containerPort: 80